<?php
// $Id: media_facebook.module,v 1.1 2010/12/06 13:45:46 njt1982 Exp $

/**
 * Implementation og hook_fbconnect_button_attr_alter().
 */
 function media_facebook_init(){
 /*********Start Run it when Installing this odule********/
 db_query("CREATE TABLE IF NOT EXISTS `facebook_url_store` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `url` longtext NOT NULL,
  `data` longtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;");
/*********Run it when Installing this odule********/
 }
function media_facebook_fbconnect_button_attr_alter(&$attr) {
  if (isset($attr['perms'])) {
    $attr['perms'] .= ',user_photos';
  }
  else {
    $attr['perms'] = 'user_photos';
  }
}

/**
 * Implementation of hook_emfield_providers().
 */
function media_facebook_emfield_providers($module, $provider = NULL) {
  // This will return a listing of all provider files supported by the module. 
  if ($module == 'emimage') {
    return drupal_system_listing("$provider\.inc$", drupal_get_path('module', 'media_facebook') ."/providers/$module", 'name', 0);
  }
}
function media_facebook_media_internet_providers() {
  return array(
    'MediaInternetFaceBookHandler' => array(
      'title' => t('Facebook'),
    ),
  );
}

