<?php

/**
 * @file media_vzaar/media_vzaar.module
 *
 * Media: Vzaar provides a stream wrapper and formatters for videos provided
 * by Vzaar, available at http://vzaar.com/.
 *
 * @TODO:
 * Tie in Vzaar API.
 * Allow editors to search for videos to display on the browser.
 * Allow editors to put in a vzaar username to display on the browser.
 * Allow editors to log in w/ their credentials.
 * Allow editors to upload videos to Vzaar.
 */

// A registry of variable_get defaults.
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'media_vzaar') . '/includes/media_vzaar.variables.inc';

// Hooks and callbacks for integrating with Styles module for display.
// @todo Can save a little overhead for people without Styles module by wrapping
//   this inside a module_exists('styles'). However, is that safe to do in
//   global context? If not, is there any down side to doing it in hook_init()?
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'media_vzaar') . '/includes/media_vzaar.styles.inc';

// Hooks and callbacks for integrating with File Entity module for display.
include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'media_vzaar') . '/includes/media_vzaar.formatters.inc';

/**
 * Implements hook_media_internet_providers().
 */
function media_vzaar_media_internet_providers() {
  $path = drupal_get_path('module', 'media_vzaar');
  return array(
    'MediaInternetVzaarHandler' => array(
      'title' => 'vzaar',
      'image' => $path . '/images/stream-vzaar.png'
    ),
  );
}

/**
 * Implements hook_stream_wrappers().
 */
function media_vzaar_stream_wrappers() {
  return array(
    'vzaar' => array(
      'name' => t('Vzaar videos'),
      'class' => 'MediaVzaarStreamWrapper',
      'description' => t('Videos provided by Vzaar.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function media_vzaar_theme($existing, $type, $theme, $path) {
  return array(
    'media_vzaar_preview_style' => array(
      'variables' => array('style_name' => NULL),
      'file' => 'media_vzaar.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_vzaar_field_formatter_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
      'file' => 'media_vzaar.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    // Note that all the variables after options are now deprecated.
    'media_vzaar_video' => array(
      'variables' => array('uri' => NULL, 'options' => array(), 'width' => NULL, 'height' => NULL, 'autoplay' => NULL, 'fullscreen' => NULL, 'related' => NULL),
      'file' => 'media_vzaar.theme.inc',
      'path' => $path . '/includes/themes',
      'template' => 'media-vzaar-video',
    ),
    'media_vzaar_embed' => array(
      'variables' => array('style_name' => NULL, 'uri' => NULL, 'alt' => NULL, 'title' => NULL),
      'file' => 'media_vzaar.theme.inc',
      'path' => $path . '/includes/themes',
    ),
    'media_vzaar_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
      'file' => 'media_vzaar.theme.inc',
      'path' => $path . '/includes/themes',
    ),
  );
}

/**
 * Implements hook_media_parse().
 *
 * @todo This hook should be deprecated. Refactor Media module to not call it
 *   any more, since media_internet should be able to automatically route to the
 *   appropriate handler.
 */
function media_vzaar_media_parse($embed_code) {
  $handler = new MediaInternetVzaarHandler($embed_code);
  return $handler->parse($embed_code);
}

/**
 * Implements hook_media_format_form_prepare_alter().
 */
function media_vzaar_media_format_form_prepare_alter(&$form, &$form_state, $media) {
  $settings = array('autosubmit' => ($media->type == "video"));
  drupal_add_js(array('media_format_form' => $settings), 'setting');
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_vzaar_ctools_plugin_api($owner, $api) {
  static $api_versions = array(
    'file_entity' => array(
      'file_default_displays' => 1,
    ),
  );
  if (isset($api_versions[$owner][$api])) {
    return array('version' => $api_versions[$owner][$api]);
  }
}
